version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/api
    ports:
      - 8000:8000
    image: app:api
    container_name: api_container
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
    container_name: postgres_db